apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  #deploy set labels
  labels:
    purpose: deploy-demo
    project: roboshop
    app: nginx 
    
spec:
  replicas: 2
  #these are the labels replicaset uses to create pod replicas this should mach pod labels
  selector:
    matchLabels:
      purpose: deploy-demo
      project: roboshop
      app: nginx 

  #pod definition
  template:
      metadata:
        labels:
          purpose: deploy-demo
          project: roboshop
          app: nginx

      spec:
        containers:
        - name: nginx
          image: nginx